yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}You are logged out{% endblock %}
{% block content %}
{% with card_header='Exit' card_body='You are logged out of your account. We are waiting for you again!' %}
{% include 'includes/card.html' %} 
{% endwith %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Sign in{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Sign in
        </div>
        <div class="card-body">
          {% include 'includes/form_errors.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Sign in
              </button>
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Forgot your password?
              </a>
            </div>
          </form>
        </div> 
      </div> 
    </div> 
  </div> 
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}The password has been changed{% endblock %}
{% block content %}
{% with card_header='The password has been changed' card_body='The password has been changed successfully' %}
{% include 'includes/card.html' %} 
{% endwith %}
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Change password{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Change password
          </div>
            <div class="card-body"> 
              {% load user_filters %}
              {% include 'includes/form_errors.html' %}
              <form method="post">
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Change password
                  </button>
                </div>
              </form>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Password reset successful{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Password recovery is complete
              </div>
              <div class="card-body">
                <p>Your password has been saved. Use it to login</p>
                <a href="{% url 'login' %}">Login</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}  

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}New password{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Enter a new password
      </div>
      <div class="card-body">
        {% include 'includes/form_errors.html' %}
        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Assign a new password
            </button>
          </div>
        </form>
      </div> 
    </div> 
  </div> 
</div> 

{% else %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Error</div>
            <div class="card-body">
                <p>The password reset link is invalid or out of date.</p>
            </div> 
        </div> 
    </div> 
</div> 
{% endif %}

{% endblock %} 

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Password reset successful{% endblock %}
{% block content %}
{% with card_header='Letter sent' card_body='Check your email, you should receive an email with a link to reset your password.' %}
{% include 'includes/card.html' %} 
{% endwith %}
{% endblock %}  

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Password reset{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            To reset your old password, enter the email address you registered with
          </div>
          <div class="card-body"> 
            {% load user_filters %}
            {% include 'includes/form_errors.html' %}
            <form method="post">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Reset password
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Register on the site{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Register</div>
          <div class="card-body">
            {% load user_filters %}
            {% include 'includes/form_errors.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Register
                </button>
              </div>
            </form>
          </div>
        </div> 
      </div> 
    </div>
  </div> 
{% endblock %}